apiVersion: v1
data:
  config.app.properties: |
    spring.redis.database=0
    spring.redis.host=redis-svc
    spring.redis.port=6379
    test.val=prodTestFile
kind: ConfigMap
metadata:
  name: config-maps
  namespace: default

---
apiVersion: v1
kind: Service
metadata:
  name: redis-swagger
  labels:
    app: redis-swagger
spec:
  type: NodePort
  selector:
    app: redis-swagger
  ports:
    - protocol: TCP
      port: 8085
      name: http
      targetPort: 8080
      nodePort: 30061

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-swagger
spec:
  selector:
    matchLabels:
      app: redis-swagger
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-swagger
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: config-maps
            items:
              - key:  config.app.properties
                path: application.prod.properties
      containers:
        - name: redis-swagger
          volumeMounts:
            - name: config-volume
              mountPath: /config
          image: bhoomikars/redis-swagger:latest
          ports:
            - containerPort: 8080

